#Expyriment 0.9.0 (Python 3.6.6), .xpe-file, coding: ISO8859-1
#date: Mon Aug 13 2018 20:20:15
#sha1: None
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Linux', node='L3460', release='4.4.0-109-generic', version='#132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018', machine='x86_64', processor='x86_64')
Time,Type,Event,Value,Detail,Detail2
270,Stimulus,presented,8
271,stderr,received,'Traceback (most recent call last):'
271,stderr,received,'  File "nbacktask_copy.py", line 81, in <module>'
271,stderr,received,'    run_trial(cnt,trial)'
271,stderr,received,'  File "nbacktask_copy.py", line 57, in run_trial'
271,stderr,received,'    s.preload()'
271,stderr,received,'  File "/home/k/workbench/cognitionExp/lib/python3.6/site-packages/expyriment/stimuli/_visual.py", line 916, in preload'
272,stderr,received,'    self._get_surface(),'
273,stderr,received,'  File "/home/k/workbench/cognitionExp/lib/python3.6/site-packages/expyriment/stimuli/_visual.py", line 404, in _get_surface'
273,stderr,received,'    tmp = self._create_surface()'
273,stderr,received,'  File "/home/k/workbench/cognitionExp/lib/python3.6/site-packages/expyriment/stimuli/_rectangle.py", line 246, in _create_surface'
273,stderr,received,'    surface.fill(self._colour)'
273,stderr,received,'TypeError: invalid color argument'
